### ISSUE TITLE
Case on module name

### ISSUE THREAD

**Issue by homer8173** [GPCsolutions/dolibarr-module-template#21]
I have try to put your module on /custom/mymodule as described in the readme
i tested it on a dolibarr 4.0.0

and there's a mismatch between the module name and the installed directory

**Comment by rdoursenaud** [comment]
Since your description is very vague, I can only guess that you've been bitten by the module ID collision.

Since Dolibarr 4.0.0 the module ID 10000 has been used for the new websites module.

You must update your module ID in the module descriptor and the related language keywords in your language files.

I just pushed an update a few hours ago to use a free ID: d702f605cd7fb148ff5ef125c1d47cb42f91cb74

**Comment by rdoursenaud** [comment]
If the issue you're facing is different please let me know and describe it in more details. Thanks.
